$(document).ready(function(){
  $("#show").click(function(){
    $(".showAnimal").show();
  });
  $("#showAnimal2").click(function(){
    $(".showSecAnimal").slideToggle();
  });
  $("#hide").click(function(){
    $(".clear").hide();
  })
});
